# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ahci" "nvme" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/b8e200bc-c09c-4560-9549-d25499d8086a";
    fsType = "ext4";
  };

  fileSystems."/media" = {
    device = "/dev/disk/by-uuid/5d86b483-cdc4-4f03-b5a0-a2d6882551e4";
    fsType = "btrfs";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/2AE4-C5B6";
    fsType = "vfat";
  };

  fileSystems."/data" = {
    device = "data";
    fsType = "zfs";
  };

  fileSystems."/data/tv shows" = {
    device = "data/tv shows";
    fsType = "zfs";
  };

  fileSystems."/data/movies" = {
    device = "data/movies";
    fsType = "zfs";
  };

  fileSystems."/data/downloads" = {
    device = "data/downloads";
    fsType = "zfs";
  };

  fileSystems."/data/vpn" = {
    device = "data/vpn";
    fsType = "zfs";
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/7c9c49c8-6ee9-4640-a4e2-99b180fbb43d";}
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
